### ISSUE TITLE
[Issue] YT music opens but doesn't load

### ISSUE THREAD

**Issue by Hachimandroid** [ginsudev/YTMusicUltimate#24]
It cant seem to load. Only a black empty screen.
Im on an Ipad9th gen ios 16

**Comment by jjjolley** [comment]
I’m on a iPhone 13 Pro FW 15.0 using TrollStore and after login I get only a black screen also.

I can see everything until after I login I just get a black screen.

**Comment by ginsudev** [comment]
I'll look into it today

**Comment by ginsudev** [comment]
Does it still happen on v1.1.14?

**Comment by Chrisss03** [comment]
Yes. Still happen on v1.1.14.

**Comment by ginsudev** [comment]
Well if I remember correctly, to fix that bug, you just need to keep opening & closing YTMusic until it lets you in. Try reboot as well. I experienced it a few months ago and that's what fixed it for me

**Comment by jjjolley** [comment]
I installed the update and it’s working perfectly for me.

**Comment by ginsudev** [comment]
Thanks for letting me know 👍

**Comment by HarshSPatel** [comment]
Installed 1.2.1 on 14 pro max running 16.0.2 , loads and logs me in but black screen is persistent. Tried several versions but same results.

**Comment by HarshSPatel** [comment]
I think YT in some region, there has been some server side change which basically prohibits us from accessing those premium features, so like selecting a specific song or playlist wouldn't work. This is true for canada for sure i can't be too sure what other regions are affected by this and the only workaround for vanced manager (android) we had was to downgrade to an older version.

So YT music features wouldn't work with this IPA, it would simply act same as a stored YT music app except this ipa would block ads.

**Comment by ginsudev** [comment]
> I think YT in some region, there has been some server side change which basically prohibits us from accessing those premium features, so like selecting a specific song or playlist wouldn't work. This is true for canada for sure i can't be too sure what other regions are affected by this and the only workaround for vanced manager (android) we had was to downgrade to an older version.
> 
> 
> 
> So YT music features wouldn't work with this IPA, it would simply act same as a stored YT music app except this ipa would block ads.

Try new version

**Comment by lupus0802** [comment]
Hey,
just found this thread. The issue also occurs on my iPhone 8 (iOS 16), I downloaded the newest version and it doesn't seem to fix it.

**Comment by gmonarque** [comment]
Iphone 11 running 15.6.1, same thing, black screen after asking for 5 artists I like

**Comment by Razorbacktrack** [comment]
v1.2.2, black screen, iP11 Pro Max, iOS 15.4.1

**Comment by Hetyey** [comment]
I was using v1.2.1, but after I reinstalled it, neither version worked any more.

**Comment by arichorn** [comment]
![B9FF98B4-3D26-4B95-85FE-8FC4CD16A683](https://user-images.githubusercontent.com/78001398/194956376-fe7ab6af-6298-48f7-b9ee-da9de3415b81.png)
I can’t load it too

**Comment by Hetyey** [comment]
Update: I left the app on my phone, and I waited. Next morning I forgot that the app was not working and I launched it and now it works fine.

**Comment by arichorn** [comment]
It was resolved too, kept restarting the app until it started to actually load YouTube Music

**Comment by mithuprince** [comment]
This issue still not solved im on my iphone Xs Ios 16 and the YTmusic is still not loading just a black screen is appearing from last 3-4 version this issue is constant :( 
hoping for a quick fix

**Comment by arichorn** [comment]
It’s temporarily there is a few ways to fix it for now
- keep restarting the app until it loads YTMusic
- Wait for awhile and then close and open the app

**Comment by ginsudev** [comment]
Another way to fix:

![image](https://user-images.githubusercontent.com/25361391/195005445-c4807c1e-8acc-4516-a215-0356bf4d543f.jpeg)

**Comment by kutibotond** [comment]
Still stuck on blank screen with version 1.2.4 on ipad air 4 with iOS 15.7.

**Comment by Annguyen1qqq** [comment]
I don't know if it works for you but try to download the official from the app store, open the official, sign in, and then open the Ultimate one.

**Comment by dayanch96** [comment]
> Still stuck on blank screen with version 1.2.4 on ipad air 4 with iOS 15.7.

Still stuck? Please let me know so we can test something that i found out about that

**Comment by kutibotond** [comment]
> > Still stuck on blank screen with version 1.2.4 on ipad air 4 with iOS 15.7.
> 
> 
> 
> Still stuck? Please let me know so we can test something that i found out about that

Yep, please share

**Comment by dayanch96** [comment]
> > > Still stuck on blank screen with version 1.2.4 on ipad air 4 with iOS 15.7.
> > 
> > 
> > Still stuck? Please let me know so we can test something that i found out about that
> 
> Yep, please share

Check IPA in my releases and freshly install it, then tap to 'Fix black screen' button in alert message at first startup app. It will open RickRoll-music which should broke that black screen but I haven't tested it. Please let me know after testing. Thanks in advance!

**Comment by dayanch96** [comment]
> I forgot to mention, that I've updated to ipados 16.1 since. I tried the original 1.2.6 ipa now and it works fine again. My intuition says the issue must have been related somehow to the later ipados versions because earlier I didn't have the black screen issue. Your ipa failed to install with AltStore for some reason.

I uploaded it from Windows, thats why AltStore can’t install it. Seems like some permissions in IPA changed.

Black screen may appear in first login, after succes logging in it won’t appear again.

**Comment by dayanch96** [comment]
> Thanks dayanch! I appreciate the fix! 🙏

Nw, black screen was fixed by PoomSmart here: https://github.com/ginsudev/YTMusicUltimate/commit/00498ecc8b181adfea1c40b44c7ad6ef259edf4a
